#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#ifdef _WIN32
#include <direct.h>
#define mkdir_compat(path) _mkdir(path)
#else
#define mkdir_compat(path) mkdir(path, 0755)
#endif

typedef struct {
    int id;
    const char *title;
    const char *category;
    const char *keywords;
    const char *description;
    const char *heading;
    const char *content;
    int link1;
    int link2;
} CorpusPage;

static CorpusPage pages[] = {
    {1, "Compiler Optimization Techniques", "Compilers", "compiler, optimization, static analysis, loop unrolling, constant folding", "An in-depth guide to modern compiler optimization passes including dead code elimination, constant folding, and vectorization.", "Compiler Construction & High-Performance Code Generation", "Modern compiler optimization techniques improve program execution speed and reduce memory consumption. Passes include static analysis, loop unrolling, constant propagation, and vectorization. Intermediate representations like SSA form facilitate transformations.", 2, 3},
    {2, "Operating System Kernel Architecture", "Operating Systems", "kernel, monolithic, microkernel, process management, scheduling", "Overview of operating system kernel architectures, process scheduling algorithms, and inter-process communication.", "Kernel Architecture and Process Management", "An operating system kernel manages hardware resources, processes, and memory. Architectural paradigms include monolithic kernels, microkernels, and hybrid kernels. Preemptive scheduling algorithms like Round Robin and Multi-Level Feedback Queues maintain fairness.", 1, 4},
    {3, "Database Storage Engines and B+ Trees", "Database Systems", "database, btree, storage engine, indexing, transactions, ACID", "Detailed examination of database storage engines, B+ tree indexing, write-ahead logging, and ACID transaction semantics.", "Relational Database Storage & Indexing", "Database storage engines organize data on disk for rapid access. B+ tree indexing structures allow O(log N) lookup, range queries, and node splitting. Write-ahead logging guarantees atomicity and durability under unexpected crashes.", 1, 5},
    {4, "Computer Networking Protocols and TCP/IP", "Networking", "tcp, ip, sockets, routing, congestion control, latency", "Understanding the TCP/IP stack, socket programming, flow control, and network routing protocols.", "Network Protocol Stack and Socket Interfaces", "The TCP/IP stack consists of application, transport, internet, and link layers. TCP provides reliable byte-stream transmission via sequence numbers, checksums, window scaling, and cubic congestion control.", 2, 6},
    {5, "Distributed Systems Consensus and Raft Protocol", "Distributed Systems", "distributed, consensus, raft, paxos, replication, fault tolerance", "A complete guide to consensus algorithms, leader election, and state machine replication in distributed systems.", "State Machine Replication with Raft Consensus", "Consensus algorithms allow distributed nodes to agree on a sequence of state transitions despite network partitions. The Raft protocol divides consensus into leader election, log replication, and safety properties.", 3, 7},
    {6, "Data Structures: Red-Black Trees and Hash Tables", "Data Structures", "data structures, hashtable, red-black tree, algorithms, complexity", "Comprehensive guide to balanced binary search trees, hash table collision resolution, and algorithmic time complexity.", "Self-Balancing Trees and High-Throughput Hash Maps", "Efficient data structures form the backbone of software systems. Red-Black trees enforce logarithmic height bounds using node colors and rotations. Hash tables provide O(1) expected time lookup using open addressing or chaining.", 4, 8},
    {7, "Asynchronous I/O and Event Loops", "System Programming", "async, event loop, epoll, kqueue, concurrency, non-blocking", "Exploration of non-blocking asynchronous I/O multiplexing using epoll, kqueue, and event-driven event loops.", "High-Performance Event-Driven Server Architectures", "Non-blocking socket I/O enables single-threaded servers to handle thousands of concurrent client connections. POSIX epoll and kqueue notify the application when sockets become readable or writable.", 5, 9},
    {8, "Garbage Collection Algorithms in Modern Runtimes", "Programming Languages", "garbage collection, mark sweep, generational, memory management", "Analyzing memory management strategies, tracing garbage collection, generational hypothesis, and concurrent compaction.", "Automatic Memory Management and Runtime Tracing", "Garbage collection automatically reclaims unreferenced heap allocations. Generational collectors exploit the observation that most objects die young. Mark-sweep and mark-compact algorithms minimize stop-the-world pauses.", 6, 10},
    {9, "Virtual Memory and Page Table Management", "Operating Systems", "virtual memory, paging, tlb, mmu, page fault", "Understanding virtual memory hardware abstraction, translation lookaside buffers, multi-level page tables, and page fault handlers.", "Memory Virtualization and Hardware Page Tables", "Virtual memory isolates process address spaces and provides transparent memory mapping. Hardware Memory Management Units translate virtual addresses to physical frames using Page Tables and TLBs.", 7, 11},
    {10, "Cryptography Principles and Public Key Infrastructure", "Security", "cryptography, RSA, AES, ECC, pki, digital signatures", "Principles of symmetric encryption, public-key cryptography, elliptic curve cryptography, and digital certificate validation.", "Modern Cryptographic Standards and Asymmetric Ciphers", "Cryptography secures communication over untrusted channels. Symmetric ciphers like AES-GCM offer fast encryption, while asymmetric ciphers like RSA and ECC enable key exchange and non-repudiable digital signatures.", 8, 12},
    {11, "Machine Learning Gradient Descent and Neural Networks", "Machine Learning", "machine learning, neural networks, backpropagation, gradient descent, loss function", "Mathematical foundations of artificial neural networks, backpropagation, and stochastic gradient descent optimization.", "Deep Neural Networks and Optimization Dynamics", "Neural networks approximate non-linear functions through layers of connected artificial neurons. Backpropagation computes partial derivatives of the loss function using the calculus chain rule.", 9, 13},
    {12, "Lexical Analysis and Fast Finite Automata", "Compilers", "lexer, flex, regex, finite automata, DFA, NFA", "Building fast lexical analyzers using deterministic finite automata and regular expressions.", "Scanning and Token Generation in Compilers", "Lexical analysis breaks input source code streams into discrete tokens. Regular expressions are converted to Non-Deterministic Finite Automata and determinized into DFAs for O(N) scanning speed.", 10, 14},
    {13, "Parser Design: Recursive Descent and LR Parsing", "Compilers", "parser, recursive descent, AST, LALR, grammar, EBNF", "Design and implementation of hand-rolled recursive descent parsers and context-free EBNF grammar parsers.", "Context-Free Grammars and Abstract Syntax Tree Generation", "Parsing transforms linear token streams into hierarchical Abstract Syntax Trees. Recursive descent parsers map grammar rules directly to programming language functions.", 11, 15},
    {14, "Concurrency Synchronization Primitives", "System Programming", "mutex, spinlock, condition variable, semaphore, deadlock, atomic", "Understanding mutex locks, spinlocks, condition variables, semaphores, and memory barriers in concurrent programs.", "Thread Synchronization and Race Condition Prevention", "Multi-threaded programs require synchronization primitives to prevent data races. Mutexes enforce mutual exclusion, while condition variables allow threads to block until state predicates are satisfied.", 12, 16},
    {15, "Cache Coherence and Memory Consistency Models", "Computer Architecture", "cache coherence, MESI, memory barrier, sequential consistency, relaxed", "Detailed overview of multiprocessor cache coherence protocols like MESI and CPU memory consistency ordering.", "Hardware Multiprocessing and Cache Consistency", "Modern multi-core processors maintain unified cache views across core-local L1/L2 caches using coherence protocols like MESI. Memory barriers order load and store instructions.", 13, 17},
    {16, "Distributed Key-Value Stores and LSM Trees", "Database Systems", "lsm tree, rocksdb, key value, memtable, sstable, write amplification", "Architecture of Log-Structured Merge-Trees, memtables, SSTables, compaction, and high write throughput.", "Write-Optimized Storage with Log-Structured Merge-Trees", "LSM-Trees optimize write performance by appending writes to an in-memory memtable and sequentially flushing sorted SSTables to disk. Background compaction merges overlapping key ranges.", 14, 18},
    {17, "HTTP/2 and HTTP/3 QUIC Protocol Architecture", "Networking", "http, http2, http3, quic, multiplexing, udp, tls", "Comparing HTTP/1.1 pipeline limitations with HTTP/2 binary frame multiplexing and HTTP/3 QUIC UDP transport.", "Evolution of Modern Web Transport Protocols", "HTTP/2 introduced binary framing, header compression, and stream multiplexing over TCP. HTTP/3 replaces TCP with QUIC over UDP to eliminate head-of-line blocking.", 15, 19},
    {18, "Abstract Data Types and Object-Oriented Design", "Software Engineering", "object oriented, encapsulation, polymorphism, abstraction, solid", "Core principles of object-oriented architecture, SOLID design patterns, and interface abstractions.", "Software Architecture Patterns and Component Interfaces", "Object-oriented design organizes software into reusable modules with well-defined contracts. SOLID principles guide component decoupling, testability, and maintainability.", 16, 20},
    {19, "Containerization and Linux Namespaces", "DevOps", "container, docker, cgroups, namespaces, isolation, chroot", "How Linux kernel namespaces, cgroups, and overlay filesystems enable lightweight containerization.", "OS-Level Virtualization and Linux Kernel Control Groups", "Containers provide lightweight execution environments by sharing the host kernel. Linux namespaces isolate process trees, network interfaces, and mount points, while cgroups cap memory and CPU resource usage.", 17, 21},
    {20, "Static Code Analysis and Abstract Interpretation", "Software Engineering", "static analysis, AST, linter, sound analysis, buffer overflow", "Detecting bugs, memory leaks, and security vulnerabilities without running the application binary.", "Automated Bug Detection and Program Verification", "Static code analysis tools inspect source code ASTs and control flow graphs to detect undefined behavior, memory leaks, and buffer overflows prior to compilation.", 18, 22},
    {21, "Graph Algorithms: Shortest Path and Topological Sorting", "Algorithms", "graph, dijkstra, bfs, dfs, topological sort, shortest path", "Classic graph traversals, Dijkstra's algorithm, A* search, and dependency resolution using topological sort.", "Graph Traversals and Pathfinding Optimization", "Graph algorithms solve pathfinding and dependency resolution problems. Dijkstra's algorithm computes single-source shortest paths in non-negative weighted graphs using priority queues.", 19, 23},
    {22, "Type Systems and Static Type Checking", "Programming Languages", "type system, type checking, inference, Hindley-Milner, generics", "Exploration of static vs dynamic typing, type inference algorithms, sound type systems, and generic programming.", "Formal Type Theory and Static Safety Guarantees", "Type systems categorize expressions to guarantee runtime safety properties. Static type checkers enforce invariant safety constraints at compile time, eliminating broad classes of runtime bugs.", 20, 24},
    {23, "GPU Computing and Parallel Matrix Multiplication", "High Performance Computing", "gpu, cuda, SIMD, opencl, parallel computing, matrix multiplication", "Accelerating computation with CUDA, GPU SIMD architecture, and high-performance parallel linear algebra.", "Massively Parallel Execution and Accelerators", "Graphics Processing Units contain thousands of execution cores designed for throughput-oriented parallel workloads. Thread blocks execute SIMD instructions over vector registers.", 21, 25},
    {24, "Microservice Architecture and API Gateways", "Distributed Systems", "microservices, api gateway, service mesh, gRPC, REST", "Designing scalable microservices, service discovery, circuit breakers, and gRPC communication.", "Decoupled Service Architectures and Network Routing", "Microservice architectures decompose monolithic applications into independently deployable services. API gateways handle authentication, request routing, and rate limiting.", 22, 26},
    {25, "Instruction Set Architectures: RISC-V vs x86", "Computer Architecture", "risc-v, x86, instruction set, pipelining, CPU, assembly", "Comparing Reduced Instruction Set Computer principles with Complex Instruction Set Computer architectures.", "CPU Pipelining and Hardware Decoding", "Instruction Set Architectures define the hardware-software boundary. RISC-V features fixed-length instructions for easy pipelining, while x86 uses variable-length instruction decoders.", 23, 27},
    {26, "Text Search Inverted Indices and Scoring", "Search Engines", "inverted index, search engine, posting list, tfidf, bm25", "Inside search engine indexing structures, term frequency calculations, posting list compression, and ranking.", "Information Retrieval Foundations and Vector Space Models", "Search engine backends build inverted indices mapping normalized terms to postings lists containing document identifiers, term frequencies, and positions.", 24, 28},
    {27, "POSIX System Calls and Low-Level I/O", "System Programming", "posix, system call, read, write, open, file descriptor", "Interfacing directly with UNIX kernels using POSIX system calls, file descriptors, and socket descriptors.", "UNIX Kernel Interface and File Operations", "POSIX system calls bridge user applications and kernel space. Operations like open, read, write, and select operate on low-level integer file descriptors.", 25, 29},
    {28, "C Memory Allocation Internals and Heap Fragmentation", "C Programming", "malloc, free, ptmalloc, heap, fragmentation, brk, mmap", "How heap allocators manage dynamic memory, maintain free lists, handle alignment, and prevent fragmentation.", "Dynamic Memory Allocator Design in C", "Standard library memory functions like malloc and free manage heap memory requested from the OS via sbrk or mmap. Allocators use segregated free lists and boundary tags.", 26, 30},
    {29, "Modern Web Frontends and Client-Side State Management", "Web Development", "react, client state, virtual dom, typescript, hydration", "Building scalable user interfaces with component-based frameworks, typed API state, and virtual DOM rendering.", "Declarative User Interfaces and Single Page Applications", "Modern client applications decouple state management from DOM manipulation. Component trees re-render reactively when application state changes.", 27, 31},
    {30, "Software Testing Strategies: Unit, Integration, Fuzzing", "Software Engineering", "testing, unit test, integration test, fuzzing, valgrind, sanitizers", "Comprehensive software verification methods including unit tests, integration suites, property fuzzing, and sanitizers.", "Quality Assurance, Dynamic Analysis, and Fuzz Testing", "Testing validates software correctness across development phases. AddressSanitizer and Valgrind detect memory corruption bugs, while libFuzzer uncovers edge-case crashes.", 28, 32},
    {31, "Binary File Persistence and Checksum Integrity", "Storage Systems", "binary format, crc32, persistence, endianness, serialization", "Designing custom binary file formats with magic headers, payload versioning, and CRC32 checksum validation.", "Durable Data Serialization and Corruption Recovery", "Binary storage formats eliminate parsing overhead while providing compact representations. File headers include magic byte signatures, schema version numbers, and CRC32 footers.", 29, 33},
    {32, "Regular Expressions and Thompson's NFA Algorithm", "Algorithms", "regex, NFA, DFA, thompson algorithm, pattern matching", "Converting regular expressions into non-deterministic finite automata using Thompson's construction algorithm.", "Finite State Machines and Fast Pattern Matching", "Regular expression matching uses state machines to match string patterns in linear time without exponential backtracking.", 30, 34},
    {33, "Linear Algebra for Machine Learning and Computer Graphics", "Mathematics", "linear algebra, matrix, vector, eigenvalues, SVD", "Essential linear algebra concepts including matrix transformations, eigenvectors, and singular value decomposition.", "Vector Spaces, Transformations, and Matrix Factorization", "Linear algebra supplies the mathematical framework for multi-dimensional graphics transformations and machine learning feature projections.", 31, 35},
    {34, "Thread Pools and Task Queue Architectures", "System Programming", "thread pool, work stealing, task queue, condition variable, worker", "Implementing worker thread pools, synchronized work queues, and work-stealing schedulers for concurrent tasks.", "Concurrent Work Execution and Thread Reuse", "Thread creation incurs kernel stack allocation overhead. Thread pools maintain worker threads that pop jobs from a shared queue.", 32, 36},
    {35, "Compiler Intermediate Representations and SSA Form", "Compilers", "compiler, SSA form, intermediate representation, basic block, LLVM", "Static Single Assignment form, control flow graphs, basic blocks, and compiler IR optimization passes.", "Control Flow Analysis and Program Transformation", "Compiler intermediate representations convert ASTs into linear instructions organized into basic blocks and control flow graphs.", 33, 37},
    {36, "Functional Programming Concepts: Pure Functions and Immutability", "Programming Languages", "functional programming, immutability, pure functions, closures, monads", "Core functional programming principles, higher-order functions, lazy evaluation, and algebraic data types.", "Immutable State Transitions and Higher-Order Functions", "Functional programming treats computation as the evaluation of mathematical functions, avoiding mutable state and side effects.", 34, 38},
    {37, "Computer Graphics Pipeline and Rasterization", "Graphics", "graphics pipeline, rasterization, shader, opengl, fragment", "The 3D graphics rendering pipeline from vertex processing to fragment shading and framebuffers.", "3D Rendering Hardware and Shader Execution", "Graphics pipelines transform 3D geometric primitives into 2D screen pixels through vertex transformation, clipping, and fragment shading.", 35, 39},
    {38, "Network Congestion Control Algorithms", "Networking", "congestion control, TCP cubic, BBR, packet loss, throughput", "Analyzing network congestion management, TCP CUBIC sliding window growth, and Google's BBR bottleneck algorithm.", "Transport Layer Bandwidth and Latency Optimization", "Congestion control algorithms adjust transmission rates to match available network path bandwidth without inducing bufferbloat.", 36, 40},
    {39, "Relational Query Optimization and Execution Plans", "Database Systems", "query optimization, relational algebra, execution plan, join algorithms", "How relational query optimizers convert SQL queries into physical execution plans using cost models.", "Relational Algebra Transformations and Cost-Based Optimizers", "Database query optimizers choose optimal physical execution plans using statistics and relational algebra equivalences.", 37, 41},
    {40, "Software Security Vulnerabilities: Buffer Overflows and Mitigation", "Security", "security, buffer overflow, ASLR, DEP, stack canary", "Understanding memory safety flaws, stack buffer overflows, return-oriented programming, and OS mitigations.", "Memory Corruption Exploits and Defense Mechanisms", "Buffer overflows occur when writes exceed stack buffer boundaries. Mitigations include ASLR, non-executable stacks, and stack canaries.", 38, 42},
    {41, "Distributed Consensus with Paxos", "Distributed Systems", "paxos, consensus, distributed systems, quorum, leader election", "Mathematical proof and implementation details of Leslie Lamport's classic Paxos consensus algorithm.", "Fault-Tolerant Distributed Agreement Protocols", "Paxos guarantees fault-tolerant consensus across networks with message loss and delay through prepare and accept proposal phases.", 39, 43},
    {42, "C Standard Library Fundamentals and POSIX Extensions", "C Programming", "c standard, stdlib, string.h, stdio.h, posix, c17", "Deep dive into C17 standard library facilities, memory safety, string manipulation, and file streams.", "Standard Library Functions and Portable C Coding", "The C standard library provides cross-platform abstractions for memory management, string operations, and formatted I/O.", 40, 44},
    {43, "Software Performance Profiling and CPU Flame Graphs", "Performance", "perf, profiling, flame graph, CPU cache, latency", "Locating CPU bottlenecks using sampling profilers, call stack visualization, and CPU cache performance counters.", "Performance Diagnostics and Execution Benchmarking", "Sampling profilers capture stack traces to identify hot functions and CPU performance bottlenecks.", 41, 45},
    {44, "Microservices Service Discovery and Load Balancing", "Distributed Systems", "service discovery, load balancing, DNS, proxy, nginx", "Routing traffic dynamically across ephemeral microservice instances using client-side and server-side load balancers.", "Dynamic Service Routing and Traffic Distribution", "Service discovery tracks active IP addresses for dynamic microservice instances, balancing load across backend instances.", 42, 46},
    {45, "Unsupervised Machine Learning and Clustering Algorithms", "Machine Learning", "clustering, kmeans, PCA, unsupervised learning, dimensionality reduction", "Discovering patterns in unlabeled data using K-Means clustering, hierarchical clustering, and Principal Component Analysis.", "Data Clustering and Dimensionality Reduction", "Unsupervised learning groups data points by feature similarity using distance metrics and vector projections.", 43, 47},
    {46, "Code Formatting, Linting, and CI/CD Automation", "DevOps", "ci cd, github actions, clang-format, linting, automation", "Automating code style enforcement, automated builds, and continuous integration pipelines.", "Continuous Integration and Software Quality Pipelines", "Continuous integration pipelines compile code, run static analysis linters, and execute unit tests on every commit.", 44, 48},
    {47, "Data Compression Algorithms: Huffman and LZ77", "Algorithms", "huffman, lz77, compression, deflate, entropy coding", "Lossless data compression using variable-length Huffman prefix codes and LZ77 sliding window dictionary encoding.", "Entropy Reduction and Lossless Data Compression", "Data compression algorithms eliminate redundancy in binary streams. Huffman coding assigns shorter bit codes to frequent characters.", 45, 49},
    {48, "Domain-Driven Design and Software Architecture", "Software Engineering", "domain driven design, DDD, bounded context, aggregate, entity", "Structuring complex software domain models using bounded contexts, entities, value objects, and domain events.", "Domain Modeling and Architectural Boundaries", "Domain-Driven Design aligns software domain models with business domain expert mental models.", 46, 50},
    {49, "Operating System Memory Swapping and Virtual Memory Thrashing", "Operating Systems", "swapping, thrashing, page replacement, LRU, working set", "How operating systems swap anonymous memory pages to disk and manage working set sizes to prevent thrashing.", "Page Replacement Policies and Memory Overcommit", "When physical memory is exhausted, page replacement algorithms evict inactive physical frames to swap space.", 47, 51},
    {50, "CWeb Search Engine Architecture and Design Specification", "Search Engines", "cweb, search engine, inverted index, bm25, react native", "Engineering specification overview of CWeb search engine, C backend, React Native client, and custom ranking.", "Custom High-Performance C Search Engine", "CWeb is a self-hosted search engine backend written in pure C paired with a React Native mobile/web frontend application.", 48, 52},
    {51, "RESTful API Design Standards and JSON Formatting", "Web Development", "rest, api, json, http status, web services", "Designing scalable REST APIs with strict HTTP status codes, structured JSON payloads, and clean resource routing.", "Web API Contracts and JSON Data Serialization", "RESTful web APIs expose resource endpoints accessed via standard HTTP verbs (GET, POST, PUT, DELETE).", 49, 1},
    {52, "Software Maintenance, Refactoring, and Legacy Code", "Software Engineering", "refactoring, legacy code, technical debt, code smells, maintenance", "Techniques for refactoring complex legacy codebases, preserving existing test contracts, and reducing technical debt.", "Technical Debt Management and Structural Code Refactoring", "Refactoring improves internal software structure without altering external functional behavior.", 50, 2}
};

int main(void) {
    mkdir_compat("./data");
    mkdir_compat("./data/pages");

    size_t count = sizeof(pages) / sizeof(pages[0]);
    for (size_t i = 0; i < count; i++) {
        char filepath[512];
        snprintf(filepath, sizeof(filepath), "./data/pages/page_%d.html", pages[i].id);

        FILE *fp = fopen(filepath, "w");
        if (fp) {
            fprintf(fp,
                    "<!DOCTYPE html>\n"
                    "<html lang=\"en\">\n"
                    "<head>\n"
                    "    <meta charset=\"UTF-8\">\n"
                    "    <title>%s</title>\n"
                    "    <meta name=\"category\" content=\"%s\">\n"
                    "    <meta name=\"keywords\" content=\"%s\">\n"
                    "    <meta name=\"description\" content=\"%s\">\n"
                    "</head>\n"
                    "<body>\n"
                    "    <h1>%s</h1>\n"
                    "    <p>%s</p>\n"
                    "    <h2>Related Engineering Topics</h2>\n"
                    "    <p>Read more on related architecture topics in <a href=\"/page/%d\">Document #%d</a> and <a href=\"/page/%d\">Document #%d</a>.</p>\n"
                    "</body>\n"
                    "</html>\n",
                    pages[i].title, pages[i].category, pages[i].keywords, pages[i].description,
                    pages[i].heading, pages[i].content, pages[i].link1, pages[i].link1, pages[i].link2, pages[i].link2);
            fclose(fp);
        }
    }
    printf("Successfully seeded %zu HTML document pages in ./data/pages/\n", count);
    return 0;
}
